// const demoImage =
//   "https://res.cloudinary.com/stark-and-nfly/image/upload/v1780586906/one-bedroom-premium-houseboat-alleppey_n6fvfp.jpg";

export const boats = [
  {
    id: "ahb-001",
    name: "AHB-001",
    type: "Premium",
    bedrooms: 4,
    price: "₹12,000",
    unit: '/night',
    ac: true,
    pool: false,
    tag: "Most Popular",
    desc: 'Private upper deck, jacuzzi, gourmet Kerala cuisine, and panoramic backwater views.',
    image: "https://res.cloudinary.com/stark-and-nfly/image/upload/v1781173520/IMG-20260603-WA0026.jpg_txdhlq.jpg",
  },
  {
    id: "ahb-002",
    name: "AHB-002",
    type: "Deluxe",
    bedrooms: 2,
    price: "₹9,000",
    unit: '/night',
    ac: false,
    pool: false,
    tag: "Couple Favourite",
    desc: 'Private upper deck, jacuzzi, gourmet Kerala cuisine, and panoramic backwater views.',
    image: "https://res.cloudinary.com/stark-and-nfly/image/upload/v1781176043/IMG-20251216-WA0027.jpg_m6gv5t.jpg",
  },
  {
    id: "ahb-003",
    name: "AHB-003",
    type: "Deluxe",
    bedrooms: 3,
    price: "₹9,000",
    unit: '/night',
    ac: false,
    pool: false,
    tag: "Family Recommended",
    desc: 'Private upper deck, jacuzzi, gourmet Kerala cuisine, and panoramic backwater views.',
    image: "https://res.cloudinary.com/stark-and-nfly/image/upload/v1781179273/IMG-20260518-WA0038.jpg_verhuy.jpg",
  },
  {
    id: "ahb-004",
    name: "AHB-004",
    type: "Premium",
    bedrooms: 3,
    price: "₹12,000",
    unit: '/night',
    ac: true,
    pool: false,
    tag: "Couple Recommended",
    desc: 'Private upper deck, jacuzzi, gourmet Kerala cuisine, and panoramic backwater views.',
    image: "https://res.cloudinary.com/stark-and-nfly/image/upload/v1781203238/IMG-20260505-WA0042.jpg_cfs4np.jpg",
  },
  {
    id: "ahb-005",
    name: "AHB-005",
    type: "Premium",
    bedrooms: 1,
    price: "₹12,000",
    unit: '/night',
    ac: true,
    pool: false,
    tag: "Couple Recommended",
    desc: 'Private upper deck, jacuzzi, gourmet Kerala cuisine, and panoramic backwater views.',
    image: "https://res.cloudinary.com/stark-and-nfly/image/upload/v1781203992/IMG-20230322-WA0009.jpg_xeyrtv.jpg",
  },
  {
    id: "ahb-006",
    name: "AHB-006",
    type: "Deluxe",
    bedrooms: 7,
    price: "₹9,000",
    unit: '/night',
    ac: false,
    pool: false,
    tag: "Couple Recommended",
    desc: 'Private upper deck, jacuzzi, gourmet Kerala cuisine, and panoramic backwater views.',
    image: "https://res.cloudinary.com/stark-and-nfly/image/upload/v1781204495/IMG-20230921-WA0006.jpg_viov4y.jpg",
  },
]