
// const demoImage =
// "https://res.cloudinary.com/stark-and-nfly/image/upload/v1780586906/one-bedroom-premium-houseboat-alleppey_n6fvfp.jpg";

export const boats = [
  {
    id: "ahb-001",
    name: "AHB-001",
    type: "Premium",
    bedrooms: 4,
    price: "₹12,000",
    unit: "/night",
    ac: true,
    pool: false,
    tag: "Best Seller",
    desc: "Spacious premium houseboat with elegant interiors, scenic cruising routes, and authentic Kerala hospitality.",
    image: "https://res.cloudinary.com/stark-and-nfly/image/upload/v1781173520/IMG-20260603-WA0026.jpg_txdhlq.jpg",
  },
  {
    id: "ahb-002",
    name: "AHB-002",
    type: "Deluxe",
    bedrooms: 2,
    price: "₹9,000",
    unit: "/night",
    ac: true,
    pool: false,
    tag: "Honeymoon Pick",
    desc: "A cozy deluxe houseboat designed for couples seeking privacy and a peaceful backwater escape.",
    image: "https://res.cloudinary.com/stark-and-nfly/image/upload/v1781176043/IMG-20251216-WA0027.jpg_m6gv5t.jpg",
  },
  {
    id: "ahb-003",
    name: "AHB-003",
    type: "Deluxe",
    bedrooms: 3,
    price: "₹9,000",
    unit: "/night",
    ac: true,
    pool: false,
    tag: "Family Choice",
    desc: "Comfortable family houseboat offering village canal cruises and unforgettable Kerala experiences.",
    image: "https://res.cloudinary.com/stark-and-nfly/image/upload/v1781179273/IMG-20260518-WA0038.jpg_verhuy.jpg",
  },
  {
    id: "ahb-004",
    name: "AHB-004",
    type: "Premium",
    bedrooms: 3,
    price: "₹12,000",
    unit: "/night",
    ac: true,
    pool: false,
    tag: "Premium Stay",
    desc: "Modern premium houseboat with stylish décor and spectacular sunset cruising views.",
    image: "https://res.cloudinary.com/stark-and-nfly/image/upload/v1781203238/IMG-20260505-WA0042.jpg_cfs4np.jpg",
  },
  {
    id: "ahb-005",
    name: "AHB-005",
    type: "Premium",
    bedrooms: 1,
    price: "₹12,000",
    unit: "/night",
    ac: true,
    pool: false,
    tag: "Romantic Escape",
    desc: "Private one-bedroom premium retreat ideal for honeymooners and anniversary celebrations.",
    image: "https://res.cloudinary.com/stark-and-nfly/image/upload/v1781203992/IMG-20230322-WA0009.jpg_xeyrtv.jpg",
  },
  {
    id: "ahb-006",
    name: "AHB-006",
    type: "Deluxe",
    bedrooms: 7,
    price: "₹9,000",
    unit: "/night",
    ac: true,
    pool: false,
    tag: "Group Favourite",
    desc: "Large deluxe houseboat perfect for family gatherings, reunions, and celebrations.",
    image: "https://res.cloudinary.com/stark-and-nfly/image/upload/v1781204495/IMG-20230921-WA0006.jpg_viov4y.jpg",
  },
  {
    id: "ahb-007",
    name: "AHB-007",
    type: "Premium",
    bedrooms: 2,
    price: "₹12,000",
    unit: "/night",
    ac: true,
    pool: false,
    tag: "Executive Choice",
    desc: "Premium backwater stay featuring spacious decks and refined Kerala hospitality.",
    image: "https://res.cloudinary.com/stark-and-nfly/image/upload/v1781239989/IMG-20260401-WA0005.jpg_ewn5w5.jpg",
  },
  {
    id: "ahb-008",
    name: "AHB-008",
    type: "Deluxe",
    bedrooms: 8,
    price: "₹9,000",
    unit: "/night",
    ac: true,
    pool: false,
    tag: "Large Group Special",
    desc: "Spacious multi-bedroom houseboat built for corporate outings and large family vacations.",
    image: "https://res.cloudinary.com/stark-and-nfly/image/upload/v1781241781/IMG-20251021-WA0045.jpg_rlird9.jpg",
  },
];
