const demoImage =
  "https://res.cloudinary.com/stark-and-nfly/image/upload/v1780586906/one-bedroom-premium-houseboat-alleppey_n6fvfp.jpg";

export const boats = [
  {
    id: "royal-lotus",
    name: "Royal Lotus Premium",
    type: "Luxury",
    bedrooms: 2,
    price: "₹12,000",
    ac: true,
    pool: false,
    tag: "Most Popular",
    image: demoImage,
  },
  {
    id: "honeymoon-blossom",
    name: "Blossom Honeymoon",
    type: "Deluxe",
    bedrooms: 1,
    price: "₹9,500",
    ac: true,
    pool: false,
    tag: "Couples Pick",
    image: demoImage,
  },
  {
    id: "grand-family",
    name: "Grand Family Cruiser",
    type: "Premium",
    bedrooms: 3,
    price: "₹15,000",
    ac: true,
    pool: false,
    tag: "Best for Families",
    image: demoImage,
  },
  {
    id: "classic-deluxe",
    name: "Classic Deluxe",
    type: "Deluxe",
    bedrooms: 1,
    price: "₹5,500",
    ac: true,
    pool: false,
    tag: "Best Value",
    image: demoImage,
  },
  {
    id: "pearl-premium",
    name: "Pearl Premium",
    type: "Premium",
    bedrooms: 2,
    price: "₹8,000",
    ac: true,
    pool: false,
    tag: null,
    image: demoImage,
  },
  {
    id: "emerald-luxury",
    name: "Emerald Luxury",
    type: "Luxury",
    bedrooms: 2,
    price: "₹11,500",
    ac: true,
    pool: false,
    tag: null,
    image: demoImage,
  },
  {
    id: "sunset-premium",
    name: "Sunset Premium",
    type: "Premium",
    bedrooms: 2,
    price: "₹8,500",
    ac: true,
    pool: false,
    tag: "Sunset Cruise",
    image: demoImage,
  },
  {
    id: "paradise-family",
    name: "Paradise Family",
    type: "Deluxe",
    bedrooms: 4,
    price: "₹18,000",
    ac: true,
    pool: false,
    tag: "Large Group",
    image: demoImage,
  },
];