export const featuredBoats = [
  {
    id: 'royal-lotus',
    name: 'Royal Lotus',
    type: 'Luxury',
    bedrooms: 2,
    price: '₹12,000',
    unit: '/night',
    tag: 'Most Popular',
    desc: 'Private upper deck, jacuzzi, gourmet Kerala cuisine, and panoramic backwater views.',
    color: '#c9973a',
  },
  {
    id: 'honeymoon-blossom',
    name: 'Blossom Retreat',
    type: 'Honeymoon',
    bedrooms: 1,
    price: '₹9,500',
    unit: '/night',
    tag: 'Couples Favourite',
    desc: 'Floral décor, rose-petal bath, candlelight dinner, and private sun-deck for two.',
    color: '#d97b8a',
  },
  {
    id: 'grand-family',
    name: 'Grand Family',
    type: 'Family',
    bedrooms: 3,
    price: '₹15,000',
    unit: '/night',
    tag: 'Best for Groups',
    desc: 'Three spacious bedrooms, sundeck, children-friendly amenities, and a dedicated chef.',
    color: '#2a8a82',
  },
  {
    id: 'classic-deluxe',
    name: 'Classic Deluxe',
    type: 'Deluxe',
    bedrooms: 1,
    price: '₹5,500',
    unit: '/night',
    tag: 'Best Value',
    desc: 'Comfortable AC cabin, attached bath, traditional Kerala meals, and scenic route.',
    color: '#5a7a6a',
  },
]
