export const packages = [
  {
    id: 'day-cruise',
    icon: '☀️',
    name: 'Day Cruise',
    duration: '12:00 AM – 5:00 PM',
    color: 'var(--sunrise)',
    prices: [
      { tier: 'Deluxe', price: '₹8,000', pax: 2 },
      { tier: 'Premium', price: '₹10,000', pax: 2 },
      { tier: 'Luxury', price: '₹15,000', pax: 2 },
    ],
    includes: ['Welcome Drink', 'Lunch (Kerala Cuisine)', 'Evening Tea & Snacks', 'Sightseeing Cruise', 'Life Jackets', 'Professional Crew'],
    popular: false,
    desc: 'Perfect for day-trippers. Explore the backwaters and return by evening. Ideal for families and groups visiting Alleppey.',
  },
  {
    id: 'overnight',
    icon: '🌙',
    name: 'Overnight Stay',
    duration: '12:00 PM – 9:00 AM',
    color: 'var(--ocean-bright)',
    prices: [
      { tier: 'Deluxe', price: '₹9,000', pax: 2 },
      { tier: 'Premium', price: '₹12,000', pax: 2 },
      { tier: 'Luxury', price: '₹18,000', pax: 2 },
    ],
    includes: ['All Meals (Lunch + Dinner + Breakfast)', 'Welcome Drink', 'Evening Tea', 'AC Bedroom(s)', 'Overnight Mooring', 'Fishing Experience', 'Morning Sunrise Cruise'],
    popular: true,
    desc: 'Our most popular package. Sleep aboard the houseboat, wake up to the serene sounds of the backwaters, and enjoy a full Kerala culinary experience.',
  },
  {
    id: 'honeymoon',
    icon: '💕',
    name: 'Honeymoon Package',
    duration: '12:00 PM – 9:00 AM',
    color: 'var(--coral)',
    prices: [
      { tier: 'Premium', price: '₹12,000', pax: 2 },
      { tier: 'Luxury', price: '₹18,000', pax: 2 },
    ],
    includes: ['Rose Petal Decoration', 'Candlelight Dinner', 'Welcome Champagne / Juice', 'Honeymoon Cake', 'Special Turn-down Service', 'All Meals', 'Private Sun Deck', 'Couple Photography Session'],
    popular: false,
    desc: 'A specially curated romantic experience for newlyweds. Floral décor, candlelight, special meals, and a private sunset cruise.',
  },
  {
    id: 'group',
    icon: '👨‍👩‍👧‍👦',
    name: 'Group / Family Package',
    duration: 'Flexible Duration',
    color: 'var(--jungle)',
    prices: [
      { tier: 'Day Cruise Up to', price: '₹1,000 / Head', pax: 15 },
      { tier: 'Over Night Up to', price: '₹2,500 / Head', pax: 6 },
    ],
    includes: ['Extra per head ₹800  & ₹1,800 ','Multiple Bedrooms', 'All Meals for Group', 'Dedicated Chef', 'Spacious Sun Deck', 'BBQ Night', 'Group Activities', 'Special Decoration on Request'],
    popular: false,
    desc: 'Perfect for family gatherings, corporate outings, and large groups. Custom menus, spacious decks, and flexible arrangements.',
  },
]
